In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name' : [ 'A' , 'B' , 'C' , 'D' , 'E' , 'F' , 'G' , 'H' ],
    'English': [ 85, 90, np.nan, 40, 100, 95, 200, 60 ],
    'Science': [80, np.nan, 70, 45, 90, 85, 88, 300 ],
    'Math' : [75, 85, 65, np.nan, 95, 90, 92, 55],
    'Attendance' : [90, 95, 85, 60, np.nan, 98, 40, 88],
    'Gender' : [ 'Male' , 'm' , 'male' , 'Male' , 'Male' , 'm' , 'male' , 'Male' ]    
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

  Name  English  Science  Math  Attendance Gender
0    A     85.0     80.0  75.0        90.0   Male
1    B     90.0      NaN  85.0        95.0      m
2    C      NaN     70.0  65.0        85.0   male
3    D     40.0     45.0   NaN        60.0   Male
4    E    100.0     90.0  95.0         NaN   Male
5    F     95.0     85.0  90.0        98.0      m
6    G    200.0     88.0  92.0        40.0   male
7    H     60.0    300.0  55.0        88.0   Male

In [5]:
df.isnull()

    Name  English  Science   Math  Attendance  Gender
0  False    False    False  False       False   False
1  False    False     True  False       False   False
2  False     True    False  False       False   False
3  False    False    False   True       False   False
4  False    False    False  False        True   False
5  False    False    False  False       False   False
6  False    False    False  False       False   False
7  False    False    False  False       False   False

In [6]:
df.isnull().sum()

Name          0
English       1
Science       1
Math          1
Attendance    1
Gender        0
dtype: int64

In [7]:
df['English'] = df['English'].fillna( df['English'].mean() )
df['Science'] = df['Science'].fillna( df['Science'].mean() )
df['Math'] = df['Math'].fillna( df['Math'].mean() )
df['Attendance'] = df['Attendance'].fillna( df['Attendance'].mean() )

In [8]:
df

  Name     English     Science       Math  Attendance Gender
0    A   85.000000   80.000000  75.000000   90.000000   Male
1    B   90.000000  108.285714  85.000000   95.000000      m
2    C   95.714286   70.000000  65.000000   85.000000   male
3    D   40.000000   45.000000  79.571429   60.000000   Male
4    E  100.000000   90.000000  95.000000   79.428571   Male
5    F   95.000000   85.000000  90.000000   98.000000      m
6    G  200.000000   88.000000  92.000000   40.000000   male
7    H   60.000000  300.000000  55.000000   88.000000   Male

In [9]:
df.isnull().sum()

Name          0
English       0
Science       0
Math          0
Attendance    0
Gender        0
dtype: int64

In [10]:
df['English'] = df['English'].clip(0,100)

In [12]:
df['Gender'] = df['Gender'].str.lower()
df['Gender'] = df['Gender'].replace({
    'male' : 'Male',
    'm' : 'Male'
})

In [13]:
df

  Name     English     Science       Math  Attendance Gender
0    A   85.000000   80.000000  75.000000   90.000000   Male
1    B   90.000000  108.285714  85.000000   95.000000   Male
2    C   95.714286   70.000000  65.000000   85.000000   Male
3    D   40.000000   45.000000  79.571429   60.000000   Male
4    E  100.000000   90.000000  95.000000   79.428571   Male
5    F   95.000000   85.000000  90.000000   98.000000   Male
6    G  100.000000   88.000000  92.000000   40.000000   Male
7    H   60.000000  300.000000  55.000000   88.000000   Male

In [20]:
Q1 = df[['English','Science','Math','Attendance']].quantile(0.25)
Q3 = df[['English','Science','Math','Attendance']].quantile(0.75)
print('Q1 : \n',Q1)
print('Q3 : \n',Q3)

Q1 :
 English       78.750000
Science       77.500000
Math          72.500000
Attendance    74.571429
Name: 0.25, dtype: float64
Q3 :
 English       96.785714
Science       94.571429
Math          90.500000
Attendance    91.250000
Name: 0.75, dtype: float64

In [22]:
IQR = Q3-Q1
outlier = df[( (df[['English','Science','Math','Attendance']] < (Q1 - 1.5*IQR)) | (df[['English','Science','Math','Attendance']] > (Q3 + 1.5*IQR)) )]
outlier

  Name  English  Science  Math  Attendance Gender
0  NaN      NaN      NaN   NaN         NaN    NaN
1  NaN      NaN      NaN   NaN         NaN    NaN
2  NaN      NaN      NaN   NaN         NaN    NaN
3  NaN     40.0     45.0   NaN         NaN    NaN
4  NaN      NaN      NaN   NaN         NaN    NaN
5  NaN      NaN      NaN   NaN         NaN    NaN
6  NaN      NaN      NaN   NaN        40.0    NaN
7  NaN      NaN    300.0   NaN         NaN    NaN

In [23]:
df[['English','Science','Attendance']] = df[['English','Science','Attendance']].clip(70,100)

In [25]:
df

  Name     English  Science       Math  Attendance Gender
0    A   85.000000     80.0  75.000000   90.000000   Male
1    B   90.000000    100.0  85.000000   95.000000   Male
2    C   95.714286     70.0  65.000000   85.000000   Male
3    D   70.000000     70.0  79.571429   70.000000   Male
4    E  100.000000     90.0  95.000000   79.428571   Male
5    F   95.000000     85.0  90.000000   98.000000   Male
6    G  100.000000     88.0  92.000000   70.000000   Male
7    H   70.000000    100.0  55.000000   88.000000   Male

In [26]:
df['Attendance_log'] = np.log(df['Attendance']+1)
df

  Name     English  Science       Math  Attendance Gender  Attendance_log
0    A   85.000000     80.0  75.000000   90.000000   Male        4.510860
1    B   90.000000    100.0  85.000000   95.000000   Male        4.564348
2    C   95.714286     70.0  65.000000   85.000000   Male        4.454347
3    D   70.000000     70.0  79.571429   70.000000   Male        4.262680
4    E  100.000000     90.0  95.000000   79.428571   Male        4.387369
5    F   95.000000     85.0  90.000000   98.000000   Male        4.595120
6    G  100.000000     88.0  92.000000   70.000000   Male        4.262680
7    H   70.000000    100.0  55.000000   88.000000   Male        4.488636

In [28]:
df['Attendance_sq'] = np.sqrt(df['Attendance']+1)
df

,Name,English,Science,Math,Attendance,Gender,Attendance_log,Attendance_sq
0,A,85.000000,80.0,75.000000,90.000000,Male,4.510860,9.539392
1,B,90.000000,100.0,85.000000,95.000000,Male,4.564348,9.797959
2,C,95.714286,70.0,65.000000,85.000000,Male,4.454347,9.273618
3,D,70.000000,70.0,79.571429,70.000000,Male,4.262680,8.426150
4,E,100.000000,90.0,95.000000,79.428571,Male,4.387369,8.968198
5,F,95.000000,85.0,90.000000,98.000000,Male,4.595120,9.949874
6,G,100.000000,88.0,92.000000,70.000000,Male,4.262680,8.426150
7,H,70.000000,100.0,55.000000,88.000000,Male,4.488636,9.433981

In [29]:
df['Attendance_log'] = 1/(df['Attendance']+1)
df

,Name,English,Science,Math,Attendance,Gender,Attendance_log,Attendance_sq
0,A,85.000000,80.0,75.000000,90.000000,Male,0.010989,9.539392
1,B,90.000000,100.0,85.000000,95.000000,Male,0.010417,9.797959
2,C,95.714286,70.0,65.000000,85.000000,Male,0.011628,9.273618
3,D,70.000000,70.0,79.571429,70.000000,Male,0.014085,8.426150
4,E,100.000000,90.0,95.000000,79.428571,Male,0.012433,8.968198
5,F,95.000000,85.0,90.000000,98.000000,Male,0.010101,9.949874
6,G,100.000000,88.0,92.000000,70.000000,Male,0.014085,8.426150
7,H,70.000000,100.0,55.000000,88.000000,Male,0.011236,9.433981

In [31]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[['Attendance_sc']] = scaler.fit_transform(df[['Attendance']])
df

,Name,English,Science,Math,Attendance,Gender,Attendance_log,Attendance_sq,Attendance_sc
0,A,85.000000,80.0,75.000000,90.000000,Male,0.010989,9.539392,0.714286
1,B,90.000000,100.0,85.000000,95.000000,Male,0.010417,9.797959,0.892857
2,C,95.714286,70.0,65.000000,85.000000,Male,0.011628,9.273618,0.535714
3,D,70.000000,70.0,79.571429,70.000000,Male,0.014085,8.426150,0.000000
4,E,100.000000,90.0,95.000000,79.428571,Male,0.012433,8.968198,0.336735
5,F,95.000000,85.0,90.000000,98.000000,Male,0.010101,9.949874,1.000000
6,G,100.000000,88.0,92.000000,70.000000,Male,0.014085,8.426150,0.000000
7,H,70.000000,100.0,55.000000,88.000000,Male,0.011236,9.433981,0.642857

In [32]:
df

,Name,English,Science,Math,Attendance,Gender,Attendance_log,Attendance_sq,Attendance_sc
0,A,85.000000,80.0,75.000000,90.000000,Male,0.010989,9.539392,0.714286
1,B,90.000000,100.0,85.000000,95.000000,Male,0.010417,9.797959,0.892857
2,C,95.714286,70.0,65.000000,85.000000,Male,0.011628,9.273618,0.535714
3,D,70.000000,70.0,79.571429,70.000000,Male,0.014085,8.426150,0.000000
4,E,100.000000,90.0,95.000000,79.428571,Male,0.012433,8.968198,0.336735
5,F,95.000000,85.0,90.000000,98.000000,Male,0.010101,9.949874,1.000000
6,G,100.000000,88.0,92.000000,70.000000,Male,0.014085,8.426150,0.000000
7,H,70.000000,100.0,55.000000,88.000000,Male,0.011236,9.433981,0.642857